services:
  postgres:
    image: postgres:17

    container_name: scarf-shop-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scarf_shop

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: